version: '3'
services:
    ret2win2:
        image: ret2win2
        build: src/
        container_name: ret2win2
        network_mode: bridge
        restart: always
        ports:
            - "19004:1470"
        read_only: true
