version: '3.3'
services:
  web:
    build: .
    restart: always
    ports:
      - '15123:8989'
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo
    restart: always