version: '3'
services:
  hacktod:
    container_name: RSA0
    restart: always
    build:
      context: .
      args:
        binary: server.py
    ports:
      - "16001:5000" # exposed:local
    read_only: true